---
title: "That's my type"
---

In the following exercises, first guess what type the vector will be coerced to, then check your intuition with the `typeof()` function.

1.  `c(1, 1L, "C")`

```{r}
#| label: view-1
c(1, 1L, "C")
```

```{r}
#| label: help-1
1
1L
"C"
```

Guess: error

```{r}
#| label: check-1
typeof(c(1, 1L, "C"))
```

2.  `c(1L / 0, "A")`

```{r}
#| label: view-2
1L / 0
"A"
```

```{r}
#| label: help-2
c(1L / 0, "A")
```

Guess: char

```{r}
#| label: check-2
typeof(c(1L / 0, "A"))
```

3.  `c(1:3, 5)`

```{r}
#| label: view-3
1:3
5
```

```{r}
#| label: help-3
c(1:3, 5)
```

Guess: integer - WRONG

```{r}
#| label: check-3
typeof(c(1:3, 5))
```

4.  `c(3, "3+")`

```{r}
#| label: view-4
3
"3+"
```

```{r}
#| label: help-4
c(3, "3+")
```

Guess: char

```{r}
#| label: check-4
typeof(c(3, "3+"))
```

5.  `c(NA, TRUE)`

```{r}
#| label: view-5
NA
TRUE
```

```{r}
#| label: help-5
c(NA, TRUE)
```

Guess: neither char, integer, or double, but what?

```{r}
#| label: check-5
typeof(c(NA, TRUE))
```
